# Generated by Django 6.0.3 on 2026-05-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHelperApp', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('engine', 'Engine'), ('transmission', 'Transmission'), ('electrical', 'Electrical'), ('suspension', 'Suspension'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
