# Generated by Django 6.0.3 on 2026-05-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHelperApp', '0004_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='diy_capability',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='fuel_efficiency',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='parts_availability',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='repairability',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='resale_value',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
