# Generated by Django 6.0.3 on 2026-05-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHelperApp', '0005_rating_diy_capability_rating_fuel_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
